name: CI for Node.js project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Aqui você pode definir a versão do Node.js que deseja instalar

    - name: Install dependencies
      run: npm ci  # Usando o npm ci para instalar dependências

    - name: Run tests or start server
      run: npm start  # Rodar o servidor ou seus testes, dependendo do seu script start
